package com.sos.www.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sos.www.bean.EmergencyContact;

import com.sos.www.bean.dao.EmergencyContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emergencyContactDaoConfig;

    private final EmergencyContactDao emergencyContactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emergencyContactDaoConfig = daoConfigMap.get(EmergencyContactDao.class).clone();
        emergencyContactDaoConfig.initIdentityScope(type);

        emergencyContactDao = new EmergencyContactDao(emergencyContactDaoConfig, this);

        registerDao(EmergencyContact.class, emergencyContactDao);
    }
    
    public void clear() {
        emergencyContactDaoConfig.clearIdentityScope();
    }

    public EmergencyContactDao getEmergencyContactDao() {
        return emergencyContactDao;
    }

}
